# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Doxygen GitHub Pages Deploy Action
      # You may pin to the exact commit or the version.
      # uses: DenverCoder1/doxygen-github-pages-action@a30f9538f8ef1305aeceb563018f452c7a62d200
      uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
      with:
        # A GitHub token for pushing to the repo. Example: https://git.io/passing-token
          github_token: ${{ secrets.GITHUB_TOKEN }}
    # Branch name for pushing GitHub pages files
          #branch: # default is gh-pages
    # Folder where Doxygen will generate the HTML build files
          folder: html
    # Path of the Doxygen configuration file
          config_file: Doxyfile_test
    # Directory on the deployment branch for pushing the build files
          #target_folder: # optional
    # Version of Doxygen to install
          doxygen_version: 1.14.0
